import { Inter} from "next/font/google";
import "./globals.css";
import Navigation from "../../components/ui/Navigation";
import Footer from "../../components/ui/Footer";
import { ThemeProvider } from "next-themes";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navigation/>
        {children}
        <Footer/>
         </ThemeProvider>
      </body>
    </html>
  );
}
